# The project
project_name: Documentation
# Version number as a string
version: '1.0'
project_url: https://github.com/user/project-name

# Site theme (options: forest, ocean, horus, seagrass, sundae, slate)
theme: sundae


############ Options

# URLs
download_links:
  - text: Documentation
    subtext: v{{ version }}
    href: https://github.com/user/project-name/zipball/gh-pages
    title: zipped
  - text: Documentation Docs
    subtext: v{{ version }}.min
    href: https://github.com/user/project-name/downloads
    title: minified, gzipped
twitter_url: https://twitter.com/username

# Primary language or technology (options: javascript, css, html5)
lang: html5

# Documentation site scripts
scripts:
#  - src: //ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
#  - src: https://raw.github.com/user/project/master/script.js

# Footer quote
quote:
  quote: Ink is better than the best memory.
  cite: Chinese proverb

# Site analytics
ga_id:

# Page names
# Do not update the paths.
sections:
 - path: /index.html
   name: Overview
 - path: /reference/index.html
   name: Reference
