#########################################
# project site config

project_name: Pablo
project_url: https://github.com/dharmafly/pablo
version: '0.3.5'
# options: forest, ocean, horus, seagrass, sundae, slate
theme: horus
twitter_url: https://twitter.com/premasagar
# options: javascript, css, html5
lang: javascript
scripts:
  - src: /downloads/pablo.min.js
stylesheets:
  - url: /css/custom/custom.css
quote:
  - quote: Painting is just another way of keeping a diary.
  - cite: Pablo Picasso
# analytics
ga_id: UA-34978047-1
download_links:
  - text: pablo.js
    subtext: v{{ version }}
    href: /downloads/pablo.js
    title: Full source code, for use in development
  - text: pablo.min.js
    subtext: v{{ version }}
    href: /downloads/pablo.min.js
    title: Minified, for use in production
  - text: Edge
    subtext: (master)
    href: https://github.com/dharmafly/pablo/zipball/master
    title: Latest codebase (zip); potentially unstable
sections:
  - path: /index.html
    name: Overview
  - path: /api/index.html
    name: API
  - path: /misc/index.html
    name: Misc
  - path: /resources/index.html
    name: Resources

######## END project site config ########
